## Importing Libraries

In [188]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [189]:
credit_card_data.shape

(284807, 31)

In [190]:
#loading the dataset
credit_card_data = pd.read_csv('creditcard.csv')
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [191]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [192]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [193]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [194]:
credit_card_data.Class.value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

The dataset is highly unbalanced

In [196]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [197]:
legit.shape, fraud.shape

((284315, 31), (492, 31))

In [198]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [199]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [200]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

## Undersampling

In [202]:
legit_sample = legit.sample(n=492)

In [203]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0)

In [204]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
81422,58925.0,-0.643081,-0.245156,0.640001,-2.147810,-1.407152,-1.300101,0.023388,-0.023555,-1.852508,...,-0.104661,0.230635,-0.008130,0.668458,-0.461060,-0.383494,0.036307,-0.097153,70.00,0
186772,127247.0,2.176486,-0.672021,-1.366670,-0.716858,-0.492754,-0.599219,-0.886026,-0.118254,0.073377,...,0.200373,0.690928,0.010652,-0.865724,-0.055635,-0.038902,0.032389,-0.018376,22.00,0
154284,101023.0,1.897963,0.271574,-1.843193,3.009389,2.841204,4.444554,-0.611105,0.928532,0.500301,...,-0.076532,0.088363,0.132553,0.635761,0.145202,0.079431,-0.034407,-0.063476,7.72,0
47555,43256.0,-0.819903,1.091674,0.940492,0.017602,-0.362589,-0.373251,0.119326,0.727163,-0.564272,...,-0.137390,-0.591479,0.155073,0.118102,-0.321268,0.079533,0.113715,0.020650,24.99,0
134836,80988.0,-2.199997,-1.967269,1.433497,-1.099553,-0.195460,-0.665894,1.748622,-0.735395,-1.417810,...,-0.556492,-0.253617,1.327122,0.558407,0.737358,0.998973,-0.171104,-0.660856,290.94,0

In [205]:
new_dataset = new_dataset.reset_index(drop=True)

In [206]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,58925.0,-0.643081,-0.245156,0.640001,-2.147810,-1.407152,-1.300101,0.023388,-0.023555,-1.852508,...,-0.104661,0.230635,-0.008130,0.668458,-0.461060,-0.383494,0.036307,-0.097153,70.00,0
1,127247.0,2.176486,-0.672021,-1.366670,-0.716858,-0.492754,-0.599219,-0.886026,-0.118254,0.073377,...,0.200373,0.690928,0.010652,-0.865724,-0.055635,-0.038902,0.032389,-0.018376,22.00,0
2,101023.0,1.897963,0.271574,-1.843193,3.009389,2.841204,4.444554,-0.611105,0.928532,0.500301,...,-0.076532,0.088363,0.132553,0.635761,0.145202,0.079431,-0.034407,-0.063476,7.72,0
3,43256.0,-0.819903,1.091674,0.940492,0.017602,-0.362589,-0.373251,0.119326,0.727163,-0.564272,...,-0.137390,-0.591479,0.155073,0.118102,-0.321268,0.079533,0.113715,0.020650,24.99,0
4,80988.0,-2.199997,-1.967269,1.433497,-1.099553,-0.195460,-0.665894,1.748622,-0.735395,-1.417810,...,-0.556492,-0.253617,1.327122,0.558407,0.737358,0.998973,-0.171104,-0.660856,290.94,0

In [207]:
new_dataset.Class.value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [208]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,96841.841463,0.129363,-0.023178,-0.119458,-0.089721,0.159294,0.049614,0.043720,0.005053,-0.023435,...,0.022191,0.062665,-0.043014,-0.008103,-0.002528,0.000037,-0.008556,-0.022470,-0.022047,86.609309
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

## Splitting the data into Features & Targets

In [210]:
X = new_dataset.drop(columns='Class', axis = 1)
Y = new_dataset['Class']

In [211]:
X.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,58925.0,-0.643081,-0.245156,0.640001,-2.147810,-1.407152,-1.300101,0.023388,-0.023555,-1.852508,...,-0.447003,-0.104661,0.230635,-0.008130,0.668458,-0.461060,-0.383494,0.036307,-0.097153,70.00
1,127247.0,2.176486,-0.672021,-1.366670,-0.716858,-0.492754,-0.599219,-0.886026,-0.118254,0.073377,...,0.072614,0.200373,0.690928,0.010652,-0.865724,-0.055635,-0.038902,0.032389,-0.018376,22.00
2,101023.0,1.897963,0.271574,-1.843193,3.009389,2.841204,4.444554,-0.611105,0.928532,0.500301,...,-0.275283,-0.076532,0.088363,0.132553,0.635761,0.145202,0.079431,-0.034407,-0.063476,7.72
3,43256.0,-0.819903,1.091674,0.940492,0.017602,-0.362589,-0.373251,0.119326,0.727163,-0.564272,...,-0.095290,-0.137390,-0.591479,0.155073,0.118102,-0.321268,0.079533,0.113715,0.020650,24.99
4,80988.0,-2.199997,-1.967269,1.433497,-1.099553,-0.195460,-0.665894,1.748622,-0.735395,-1.417810,...,-0.520386,-0.556492,-0.253617,1.327122,0.558407,0.737358,0.998973,-0.171104,-0.660856,290.94

In [212]:
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

## Train Test Split

In [214]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify = Y)

In [215]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((787, 30), (197, 30), (787,), (197,))

## Model Training

In [217]:
model = LogisticRegression()
model.fit(X_train, Y_train)

C:\ProgramData\anaconda3\envs\ML_Projects\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

## Evaluation

In [219]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
training_data_accuracy

0.9377382465057179

In [220]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
test_data_accuracy

0.9289340101522843